### ISSUE TITLE
`block in timeline': undefined method `user' for #<Twitter::Streaming::FriendList:0x007fe52a5245d8> (NoMethodError)

### ISSUE THREAD

**Issue by dylanjha** [sferik/x-cli#133]
getting this error on:
`t stream timeline`

``` ruby
/Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/t-2.0.1/lib/t/stream.rb:108:in `block in timeline': undefined method `user' for #<Twitter::Streaming::FriendList:0x007fe52a5245d8> (NoMethodError)
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/client.rb:69:in `block in request'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:28:in `call'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:28:in `block in on_body'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:26:in `each'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:26:in `on_body'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:17:in `<<'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/response.rb:17:in `<<'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/connection.rb:16:in `stream'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/client.rb:72:in `request'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/twitter-5.1.1/lib/twitter/streaming/client.rb:46:in `user'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/t-2.0.1/lib/t/stream.rb:99:in `timeline'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:109:in `invoke'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:232:in `block in subcommand'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/gems/t-2.0.1/bin/t:20:in `<top (required)>'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/bin/t:23:in `load'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/bin/t:23:in `<main>'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by autonomytech** [comment]
undefined method `user_timeline' for Twitter:Module
i am using ruby 2.0.0 version  and rails 4.2.0
 @tweets = Twitter.user_timeline("gem") for this line

**Comment by autonomytech** [comment]
also using following configuration in initializer

client = Twitter::Streaming::Client.new do |config|
  config.consumer_key = 'XXXX'
  config.consumer_secret = 'XXXXX'
  config.access_token = 'XXXXX'
  config.access_token_secret = 'XXXXX'
end
plz help
