### ISSUE TITLE
Can't authorize

### ISSUE THREAD

**Issue by QuincyLarson** [sferik/x-cli#249]
When running t authorize, t fails to open the right paths on the browser. This renders installation impossible (or highly impractical). This issue was first mentioned to occur on Cygwin, but it's occuring on OSX Yosemite as well.

**Comment by chrisopedia** [comment]
I'm getting the same issue.

```bash
Enter the supplied PIN: /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:144:in `exec': No such file or directory - google-chrome (Errno::ENOENT)
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:144:in `exec_or_raise'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:123:in `block in wet_run'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:120:in `fork'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:120:in `wet_run'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb:62:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/application.rb:58:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:79:in `open'
        from /Library/Ruby/Gems/2.0.0/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
        from /Library/Ruby/Gems/2.0.0/gems/t-2.9.0/lib/t/utils.rb:108:in `open_or_print'
        from /Library/Ruby/Gems/2.0.0/gems/t-2.9.0/lib/t/cli.rb:96:in `authorize'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/t-2.9.0/bin/t:20:in `<top (required)>'
        from /usr/bin/t:23:in `load'
        from /usr/bin/t:23:in `<main>'
```

**Comment by sai43** [comment]
hey guys look at this link

https://github.com/copiousfreetime/launchy/issues/75
