### ISSUE TITLE
 undefined method `load_file' for Psych:Module (NoMethodError)

### ISSUE THREAD

**Issue by jwithington** [sferik/x-cli#258]
Hello!  First off, thanks for making t!  It's awesome.

Recently, though, something's been up and I haven't been able to get it to work. I tried installing/uninstalling. 

Here's the code that I'm getting:

`~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/t-2.9.0/lib/t/rcfile.rb:80:in`load_file': undefined method `load_file' for Psych:Module (NoMethodError)
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/t-2.9.0/lib/t/rcfile.rb:11:in`initialize'
    from ~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/singleton.rb:141:in `new'
    from ~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/singleton.rb:141:in`block in instance'
    from ~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/singleton.rb:139:in `synchronize'
    from ~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/singleton.rb:139:in`instance'
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/t-2.9.0/lib/t/cli.rb:37:in `initialize'
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:355:in`new'
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from ~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/t-2.9.0/bin/t:20:in `<top (required)>'
    from ~/.rbenv/versions/2.1.3/bin/t:23:in`load'
    from ~/.rbenv/versions/2.1.3/bin/t:23:in `<main>'`

Now, I switched my global rbenv to 1.9.3p547, and then it seemed to work.  Is it simply not working for 2.1.3?

Thanks so much!

**Comment by algritz** [comment]
Hello, I had the same issue earlier today.

My ruby version is ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]

On the otehr hand, I had psych (2.0.13, 2.0.5) installed.

I removed 2.0.13 and everything went back to normal.

**Comment by avellable** [comment]
I had to remove psych at all(2.0.8,2.0.12,2.0.13). To make it work.

**Comment by mcfiredrill** [comment]
I get this error often as well. It goes away when I remove psych, but sooner or later psych gets reinstalled (like when I want to work on rubygems.org). 
I know @sferik contributes to rubygems.org as well, wondering if you have any workarounds? :grimacing:

**Comment by jjmanzer** [comment]
yes I have hit this as well. Has anyone found a fix?

**Comment by techsethi** [comment]
gem uninstall psych

and it worked for me.
