### ISSUE TITLE
t steam timeline error

### ISSUE THREAD

**Issue by Kamil1** [sferik/x-cli#286]
There appears to be an issue with t stream timeline, with me receiving the following output when the command is inputted.

/Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Can't assign requested address - connect(2) for "199.59.148.241" port  (Errno::EADDRNOTAVAIL)
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in`new'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in`request'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:92:in `user'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/t-2.9.0/lib/t/stream.rb:146:in`timeline'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in`invoke'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/t-2.9.0/bin/t:20:in`<top (required)>'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/bin/t:23:in `load'
    from /Users/kamilkhan/.rvm/rubies/ruby-2.2.0/bin/t:23:in`<main>'
    from /Users/kamilkhan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/kamilkhan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in`<main>'

Using Mac OS X 10.11

**Comment by synthmeat** [comment]
Likewise for most streaming commands (```all``` fails completely, ```timeline``` outputs but then crashes, ...).

```
$ t stream all
/usr/local/lib/ruby/gems/2.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Can't assign requested address - connect(2) for "199.16.156.217" port  (Errno::EADDRNOTAVAIL)
        from /usr/local/lib/ruby/gems/2.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
        from /usr/local/lib/ruby/gems/2.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
        from /usr/local/lib/ruby/gems/2.1/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
        from /usr/local/lib/ruby/gems/2.1/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:58:in `sample'
        from /usr/local/lib/ruby/gems/2.1/gems/t-2.9.0/lib/t/stream.rb:43:in `all'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/lib/ruby/gems/2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/lib/ruby/gems/2.1/gems/t-2.9.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'
```

**Comment by ngscheurich** [comment]
Changing to Ruby 2.1.2 before starting the stream allows me to skirt around this issue for the time being.

`ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]`

**Comment by SteveEdson** [comment]
Same issue with `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

**Comment by yildizib** [comment]
same issue with ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Can't assign requested address - connect(2) for "199.16.156.20" port  (Errno::EADDRNOTAVAIL)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'
	from test.rb:12:in `<main>'

**Comment by larryhynes** [comment]
...aaaand, with `ruby 2.1.5`.

**Comment by larryhynes** [comment]
Ah. [Here's](https://github.com/sferik/twitter/issues/709) the real issue. There's a fix documented [here](https://github.com/animeavi/twitter/commit/6d08c5932d3033d5b69537730e02ac5905775410), it's a small change to `lib/twitter/streaming/connection.rb`.

**Comment by pmarsceill** [comment]
> Ah. Here's the real issue. There's a fix documented here...

Thanks @larryhynes. This fix worked for me. :+1:
