### ISSUE TITLE
t stream timeline: connection refused

### ISSUE THREAD

**Issue by thelumberjhack** [sferik/x-cli#287]
Hi I am experiencing this error while streaming my timeline:

``` bash
$ t stream timeline
```

After some time the app quits with this stack trace:

``` bash
/home/yannick/.gem/ruby/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection refused - connect(2) for "199.59.148.139" port  (Errno::ECONNREFUSED)
    from /home/yannick/.gem/ruby/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
    from /home/yannick/.gem/ruby/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
    from /home/yannick/.gem/ruby/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
    from /home/yannick/.gem/ruby/2.2.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:92:in `user'
    from /home/yannick/.gem/ruby/2.2.0/gems/t-2.9.0/lib/t/stream.rb:146:in `timeline'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/yannick/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/yannick/.gem/ruby/2.2.0/gems/t-2.9.0/bin/t:20:in `<top (required)>'
    from /home/yannick/.gem/ruby/2.2.0/bin/t:23:in `load'
    from /home/yannick/.gem/ruby/2.2.0/bin/t:23:in `<main>'
```

My ruby version, running on an up-to-date ArchLinux x64:

``` bash
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```

With the gem

``` bash
$ t version        
2.9.0
```

**Comment by SteveEdson** [comment]
Also getting the same issue.

Ruby:
```
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by cwonrails** [comment]
Same issue here:

Ruby:

`ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]`

**Comment by Hund** [comment]
Same here.. o/

Arch Linux (x86_64), t 2.9.0 and Ruby 2.2.3p173.

**Comment by agladders** [comment]
fix mentioned in this thread: [https://github.com/sferik/t/issues/286#issuecomment-153067380]
