### ISSUE TITLE
T stopped working after latest updates on Ubuntu/AWS 

### ISSUE THREAD

**Issue by mikkokotila** [sferik/x-cli#323]
I'm getting the below error message from an Ubuntu / AWS instance (where T used to work just fine). I can run "sudo t authorize" but no other command works.

/usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (/home/ubuntu/.trc): could not find expected ':' while scanning a simple key at line 63 column 1 (Psych::SyntaxError)
    from /usr/lib/ruby/1.9.1/psych.rb:203:in`parse_stream'
    from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from /usr/lib/ruby/1.9.1/psych.rb:127:in`load'
    from /usr/lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
    from /usr/lib/ruby/1.9.1/psych.rb:297:in`open'
    from /usr/lib/ruby/1.9.1/psych.rb:297:in `load_file'
    from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/rcfile.rb:80:in`load_file'
    from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/rcfile.rb:11:in `initialize'
    from /usr/lib/ruby/1.9.1/singleton.rb:141:in`new'
    from /usr/lib/ruby/1.9.1/singleton.rb:141:in `block in instance'
    from <internal:prelude>:10:in`synchronize'
    from /usr/lib/ruby/1.9.1/singleton.rb:139:in `instance'
    from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:37:in`initialize'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:355:in `new'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:355:in`dispatch'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /var/lib/gems/1.9.1/gems/t-2.9.0/bin/t:20:in`<top (required)>'
    from /usr/local/bin/t:23:in `load'
    from /usr/local/bin/t:23:in`<main>'

**Comment by sferik** [comment]
What Ruby version are you using?

**Comment by mikkokotila** [comment]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

With the same version T works fine on another AWS instance. 

Thanks for quick response.

**Comment by sferik** [comment]
Did you copy your `~/.trc` files onto those new instances? Is it possible those files were corrupted?

What is the output of the following command?

    ruby -e 'require "yaml"; puts YAML.load_file("#{ENV.fetch(:HOME.to_s)}/.trc").to_yaml' | head -1

**Comment by mikkokotila** [comment]
I get the output: 

/usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (/home/ubuntu/.trc): could not find expected ':' while scanning a simple key at line 63 column 1 (Psych::SyntaxError)
	from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
	from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
	from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
	from /usr/lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
	from /usr/lib/ruby/1.9.1/psych.rb:297:in `open'
	from /usr/lib/ruby/1.9.1/psych.rb:297:in `load_file'
	from -e:1:in `<main>'

**Comment by mikkokotila** [comment]
re ~/.trc 

I checked and none of the systems, 2 that are still working fine and 2 where t is not working have nothing in ~/.trc. 

Also small clarification is that I've run t on the 2 instances that are not working now just fine for 6 months.

**Comment by sferik** [comment]
I don’t think it’s possible that it’s “working just fine” on a system without a `.trc` file. It might not be stored in your home directory but it’s gotta be somewhere.

**Comment by mikkokotila** [comment]
Sorry my bad, I was looking for a folder with files in it. I do have ~/.trc and you were correct, the file is for some reason corrupted. It looks perfectly fine, but there is one newline and 'p' on the resulting new row. Once the 'p' is removed together with the newline, it works fine. In the other system the .trc file is completely empty. Will fix it later and report back. Thanks a lot, and sorry for the extra step in troubleshooting this.

**Comment by sferik** [comment]
Thank you for taking the time to report this issue.

Now that X has introduced [Pay-Per-Use API Pricing](https://x.com/i/trending/2019901839370531129), I've rewritten the `t` CLI in Rust (it has also been renamed to `x`).

If you believe this issue still applies to the new CLI, please reopen this issue or open a new one with updated details. Thank you for your understanding and your contributions to this project!
