### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by mahdi** [sferik/x-cli#416]
I receive the following error message after entering the API Key/Secret:

```
Traceback (most recent call last):
	7: from /usr/local/bin/t:23:in `<main>'
	6: from /usr/local/bin/t:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	3: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	2: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	1: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
```

**Comment by dotneet** [comment]
Duplicated
https://github.com/sferik/t/issues/402

**Comment by sferik** [comment]
Thank you for taking the time to report this issue.

Now that X has introduced [Pay-Per-Use API Pricing](https://x.com/i/trending/2019901839370531129), I've rewritten the `t` CLI in Rust (it has also been renamed to `x`).

If you believe this issue still applies to the new CLI, please reopen this issue or open a new one with updated details. Thank you for your understanding and your contributions to this project!
