### ISSUE TITLE
in `authorize': undefined method `captures' for nil:NilClass

### ISSUE THREAD

**Issue by emerikaji** [sferik/x-cli#454]
I just installed t, and was authorizing it the usual way. This error comes up right after I enter the pin.

I saw that this issue already came up, but it was for a bug in Metasearch, and it doesn't seem to be the case here, since Metasearch isn't mentioned in the error...

```
Traceback (most recent call last):
    7: from /usr/local/bin/t:23:in `<main>'
    6: from /usr/local/bin/t:23:in `load'
    5: from /var/lib/gems/2.7.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
    4: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
    3: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
    2: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
    1: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/t-3.1.0/lib/t/cli.rb:98:in `authorize': undefined method `captures' for nil:NilClass (NoMethodError)
```

**Comment by raaghav-t** [comment]
I have an identical error with the only difference being 2.7.4 rather than 2.7.0

**Comment by maxlit** [comment]
I have the same error:

/Library/Ruby/Gems/2.6.0/gems/t-3.1.0/lib/t/cli.rb:98:in `authorize': undefined method `captures' for nil:NilClass (NoMethodError)
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'
